### ISSUE TITLE
documentation broken?

### ISSUE THREAD

**Issue by riclarsson** [atmtools/typhon#181]
## Bug report
The documentation is broken.  First it demands a theme to be installed that is not installed when "pip install -e ." is run.  Second it generates an error as below

### Bug summary
Documentation behaves unexpectedly poorly

### Code for reproduction
IN BASH IN MAIN TYPHON FOLDER:

cd doc
make html
pip install sphinx_rtd_theme
make html

```python
# Paste your code here
#
#
```

### Actual outcome

Just a bunch of strange plots generated

```
# If applicable, paste the console output here
#
#
```
looking for now-outdated files... 
Exception occurred:
  File "~/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 782, in get_doctree
    with open(doctree_filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/Dropbox/Software/typhon/doc/_build/doctrees/generated/DataFileError.doctree'
The full traceback has been saved in /tmp/sphinx-err-zqk292vi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 2

NOTE:  Also a lot of errors above here with functions or files missing

### Expected outcome

I want to have a .html file generated so I can see the documentation

## Version information

  * Operating System:
  * Typhon Version:
  * Python Version:

**Comment by olemke** [comment]
Please run 'make clean' in the doc directory and see if that helps.

**Comment by riclarsson** [comment]
Thanks!.  Using "make clean" followed by "make html" results in exactly the
same error.

2018-07-11 10:57 GMT+02:00 Oliver Lemke <notifications@github.com>:

**Comment by olemke** [comment]
I think I found the problem. For the docs, you need the optional 'pint' module installed. We didn't want to impose this dependency on the users, but unfortunately it is required to build the docs. Please install it with 'pip install pint'. Then another 'make clean; make html' in the doc directory hopefully works. I'll come up with a better way for developers to get an environment including all dependencies.

**Comment by lkluft** [comment]
There is already a way to install all additional dependencies that are needed to build the documentation:

```bash
pip install .[docs]
```

The Sphinx theme was missing, but I added that 😉 Thanks for the report 👍 

Cheers,
Lukas

**Comment by riclarsson** [comment]
Neither after "pip install pint" nor after "pip install .[docs]" does "make
clean" followed by "make html" work.  The same error remains, and there is
no .html file after the command is done

2018-07-11 11:31 GMT+02:00 Lukas Kluft <notifications@github.com>:

**Comment by riclarsson** [comment]
I noticed that cartopy is not installing properly.  This requires external
software called GEOS, that I do not own.  It wants me to have version 3.3.3
of said software.  It also complains about something called "Proj4 4.9.0"

2018-07-11 11:39 GMT+02:00 Richard Larsson <ric.larsson@gmail.com>:

**Comment by olemke** [comment]
Do you have any local changes in your working copy? If so, please verify against a clean version of the current master if the error also exists there.

Next step would be to try a clean anaconda environment for testing. I have just committed an updated version of environment.yml in the toplevel typhon directory. This file can be used to install an anaconda environment without affecting your current environment. It will contain all dependencies (pint, cartopy...) which are needed to build the typhon docs. Once you have updated to the latest typhon master run the following:

`conda env create -f environment.yml -n typhontest`

This will install all dependencies for typhon into a fresh environment (env will be called 'typhontest'). Once that's done, switch to the new environment:

`conda activate typhontest`

In this environment, do the usual `pip install -e .` in typhon and then try to build the docs.

You can switch back to your original python environment with `conda deactivate`. If you don't need the testing environment anymore, delete it with `conda env remove -n typhontest`.

**Comment by riclarsson** [comment]
I still have the same error after doing all these commands.  The small
changes I made to some other files is probably not the cause.  I post below
the full sphinx error report:

# Loaded extensions:
#   alabaster (0.7.11) from
/home/larsson/anaconda3/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.doctest (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.mathjax (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinx.ext.viewcode (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.napoleon (1.7.5) from
/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   matplotlib.sphinxext.plot_directive (unknown version) from
/home/larsson/anaconda3/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py
#   typhon.utils.sphinxext (unknown version) from
/home/larsson/Dropbox/Software/typhon/typhon/utils/sphinxext.py
Traceback (most recent call last):
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/cmdline.py",
line 304, in main
    app.build(args.force_all, filenames)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/application.py",
line 331, in build
    self.builder.build_update()
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/builders/__init__.py",
line 342, in build_update
    'out of date' % len(to_build))
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/builders/__init__.py",
line 359, in build
    for docname in self.env.check_dependents(self.app, updated_docnames):
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py",
line 620, in check_dependents
    for docnames in app.emit('env-get-updated', self):
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/application.py",
line 444, in emit
    return self.events.emit(event, self, *args)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/events.py",
line 79, in emit
    results.append(callback(*args))
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 135, in get_updated_docs
    return self.assign_section_numbers(env) +
self.assign_figure_numbers(env)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 277, in assign_figure_numbers
    _walk_doc(env.config.master_doc, tuple())
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 274, in _walk_doc
    _walk_doctree(docname, doctree, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 252, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 268, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 260, in _walk_doctree
    _walk_doc(subdocname, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 274, in _walk_doc
    _walk_doctree(docname, doctree, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 252, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 252, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 268, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 260, in _walk_doctree
    _walk_doc(subdocname, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 274, in _walk_doc
    _walk_doctree(docname, doctree, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 252, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 268, in _walk_doctree
    _walk_doctree(docname, subnode, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 260, in _walk_doctree
    _walk_doc(subdocname, secnum)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/collectors/toctree.py",
line 273, in _walk_doc
    doctree = env.get_doctree(docname)
  File
"/home/larsson/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py",
line 782, in get_doctree
    with open(doctree_filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory:
'/home/larsson/Dropbox/Software/typhon/doc/_build/doctrees/generated/get_cfeatures_at_scale.doctree'

2018-07-11 14:33 GMT+02:00 Oliver Lemke <notifications@github.com>:

**Comment by riclarsson** [comment]
"conda install cartopy" works!

The output was the same in all the /tmp/*sphinx* files so I just took one
of them.

I might have failed to activate typhontest.  If so the commands you sent me
only led to the command-prompt changing from "commandtext$"  to
"(typhontest) commandtext$".

Anyways, since "conda install cartopy" works fine, I will just have to
remember for the future that cartopy cannot be installed using normal
typhon means for installations, or with the direct pip-command.  So I am
happy now.  Thanks!

2018-07-12 7:26 GMT+02:00 Oliver Lemke <notifications@github.com>:
