### ISSUE TITLE
`spareice/test_datasets.py` failing

### ISSUE THREAD

**Issue by simonpf** [atmtools/typhon#47]
### Bug summary

`spareice/test_datasets.py` is failing.

### Code for reproduction

    py.test -v typhon/tests/spareice/test_datasets.py

### Actual outcome
````
E       assert [('typhon/tes... 6, 0))), ...] == [('typhon/test... 6, 0))), ...]
E         At index 0 diff: ('typhon/tests/spareice/reference/2017/01/01/120000-180000.nc', (datetime.datetime(2017, 1, 1, 12, 0), datetime.datetime(2017, 1, 1, 12, 0))) != ('typhon/tests/spareice/reference/2017/01/01/000000-060000.nc', (datetime.datetime(2017, 1, 1, 0, 0), datetime.datetime(2017, 1, 1, 0, 0)))
E         Full diff:
E         - [('typhon/tests/spareice/reference/2017/01/01/120000-180000.nc',
E         ?                                               ^^     ^^
E         + [('typhon/tests/spareice/reference/2017/01/01/000000-060000.nc',
E         ?                                               ^^     ^^
E         -   (datetime.datetime(2017, 1, 1, 12, 0), datetime.datetime(2017, 1, 1, 12, 0))),
E         ?                                  ^^                                    ^^
E         +   (datetime.datetime(2017, 1, 1, 0, 0), datetime.datetime(2017, 1, 1, 0, 0))),
E         Detailed information truncated (25 more lines), use "-vv" to show
````

### Expected outcome

No failure.

**Comment by lkluft** [comment]
To jump on the bandwagon, it would be more robust to construct the full path to your reference files.

In practice, replacing these lines (and related ones)...
https://github.com/atmtools/typhon/blob/c361dde29d6d4c12a01827261bdbd89f83ca7a50/typhon/tests/spareice/test_datasets.py#L9-L11

... with something like
```python
from os.path import (dirname, join)

refdir = join(dirname(__file__), 'reference')
refpattern = (
    "{year}/{month}/{day}/"
    "{hour}{minute}{second}-{end_hour}{end_minute}{end_second}.nc"
)
dataset_files = join(refdir, refpattern)
```

Cheers,
Lukas

**Comment by JohnMrziglod** [comment]
Thank you Simon and Lukas! The ordering of the files was just wrong. Should be finally fixed in #50 . However, I could not reproduce the error on my machine and neither did Travis. @simonpf May I ask what machine do you use?

**Comment by lkluft** [comment]
The PR fixes the bug for me. Before I got the reported error on my Mac and thunder7.

It is possible to run `pytest` from every directory (thanks to absolute paths) and without assertion (thanks to your bug fix).

> I could not reproduce the error on my machine and neither did Travis.

Sorting can be affected by the locales (`LC_*`) on the machine.


Cheers,
Lukas

**Comment by simonpf** [comment]
hi @JohnMrziglod , 

I run xubuntu 16.04.

The test is still failing on my machine and is suspect that there is actually a bug in your code:

https://github.com/atmtools/typhon/blob/0e66f2a8525add067192b8cfea9eff0c04bd0904/typhon/spareice/datasets.py#L559-L560

As far as I understand,  you compute the argmin of a list of lists, which should use lexicographic ordering for comparison and hence will return the index which has the smallest time delta in the first element of the list. Written in this way `find_file` should actually return the 1200 - 1800 interval. From a brief look at your code, I don't think that this is what you actually want to do.

Cheers,

Simon

**Comment by JohnMrziglod** [comment]
Hi Simon,

thank you for your other bug report. The reason for this bug was that I was not clear about the method's behaviour and just wrote quick n'dirty code. It should be fixed now.

Cheers,
John
